language: node_js
sudo: false
node_js:
  - 'lts/*'

# Since Travis is running on the Ubuntu 16+
# this library is necessary
# see https://github.com/cypress-io/cypress/issues/4069#issuecomment-488816887
addons:
  apt:
    packages:
      - libgconf-2-4

cache: false

env:
  global:
    - CYPRESS_CACHE_FOLDER = "~/.cache/Cypress"
    - CC_TEST_REPORTER_ID  = "520462d600c97e0fc201b3091614e688f494433bc56ef81a02cdda1368c3060f"

install:
  - yarn install --frozen-lockfile --non-interactive

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # Run static analyzers
  - yarn lint
  - yarn eslint

  # Build packages and integration app
  - yarn build

  # Run unit, and E2E tests
  - yarn test:ci
  - yarn test:ci:e2e

# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/billy/lcov.info # Format coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi # Upload coverage/codeclimate.json
