os:
  - linux
  - osx
  - windows
language: node_js
cache: false
node_js:
  - 'lts/*'
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - yarn config set no-progress
  - yarn install --frozen-lockfile --non-interactive
script:
  # Run static analyzers
  - yarn lint
  - yarn eslint

  # Run unit, and E2E tests
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then yarn test ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then yarn e2e ; fi
  - yarn build
